project:
  type: website
  output-dir: docs

website:
  title: "SoG PGR Conference 2025"
  site-url: https://SoGPGRConference2025.github.io/SoG_PGR-Conference-2025-Webpage/
  navbar:
    background: success
    logo: "UoL Logo.jpg"
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Participation"
        menu:
          - text: "Presentation " 
            href: Presentation.qmd
          - text: "Poster"
            href: Poster.qmd
          - text: "Lightning Talk"
            href: lightning.qmd
      - text: "Programme"
        menu:
          - text: "Conference Programme" 
            href: about2.qmd
          - text: "Abstracts"
            href: presenters2.qmd
      - text: "Organisation"
        href: Organisation.qmd
      - text: "Venue"
        href: Venue.qmd
    tools:
    - icon: twitter
      href: https://x.com/SoGLeeds?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor 
  page-footer: 
    background: light
    left: "Created by Paddy Smith"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


