---
title: "Programme"
---

+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **WHEN**    | **WHAT**                                                                                                                                                                                                                           | **WHERE**                                                                                                                                                                                                                                                                          |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9:00-9:20   | Registration                                                                                                                                                                                                                       | SoG Foyer                                                                                                                                                                                                                                                                          |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9:20-9:30   | Opening Remarks - *Clare Woulds*                                                                                                                                                                                                   | Seminar Room 1                                                                                                                                                                                                                                                                     |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9:30-9:45   | Opportunities for PGRs - *Outreach Team & Pint of Science*                                                                                                                                                                         | Seminar Room 1                                                                                                                                                                                                                                                                     |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9:45-10:45  | [Session 1: Justice and Adaptation in Global Communities, Chair: Paddy Smith]{.underline}                                                                                                                                          | [Seminar Room 1](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWE2YWQ0MjctM2UyMS00M2RlLTljZTktZjBhNjdhMDdiODQ1%40thread.v2/0?context=%7b%22Tid%22%3a%22bdeaeda8-c81d-45ce-863e-5232a535b7cb%22%2c%22Oid%22%3a%22e00978be-e503-49b1-931a-507f7901b187%22%7d)              |
|             |                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                    |
|             | -   *'Abnormal justice' for non-nationals - [Lauren Cape-Davenhill](presenters.qmd#sec-lauren-cape-davenhill-sjcc)*                                                                                                                | <br>                                                                                                                                                                                                                                                                               |
|             | -   *Modelling Climate Futures and Adaptation Options for Arctic Communities - [Sanola Sandiford](presenters.qmd#sec-sanola-sandiford-egc)*                                                                                        |                                                                                                                                                                                                                                                                                    |
|             | -   *Refugee Educational Opportunities in Indonesia - [Arwanto](presenters.qmd#sec-arwanto-sjcc)*                                                                                                                                  | <br>                                                                                                                                                                                                                                                                               |
|             | -   *Co-creating local curriculum on environmental education and indigenous knowledge systems: a case study of place-based education in Chiang Mai's Schools - [Jinnawat Lertpradit](presenters.qmd#sec-jinnawat-lertpradit-sjcc)* |                                                                                                                                                                                                                                                                                    |
|             |                                                                                                                                                                                                                                    | <br>                                                                                                                                                                                                                                                                               |
|             | [Session 2: Pollution in Environment, Chair: Connie Harpur]{.underline}                                                                                                                                                            |                                                                                                                                                                                                                                                                                    |
|             |                                                                                                                                                                                                                                    | <br>                                                                                                                                                                                                                                                                               |
|             | -   *Transport Mechanisms of Microfibers and Their Effects on Soil-Plant Systems - [Zhangling Chen](presenters.qmd#sec-zhangling-chen-rbpm)*                                                                                       |                                                                                                                                                                                                                                                                                    |
|             | -   *Microplastic-induced genotoxicity in Daphnia pulex - [Tom Nash](presenters.qmd#sec-tom-nash-rbpm)*                                                                                                                            | <br>                                                                                                                                                                                                                                                                               |
|             | -   *Quantifying Methane Fluxes and Environmental Influences in UK Freshwater Ecosystems: A Spatio-Temporal Study- [T. Kulangana](presenters.qmd#sec-t.-kulangana-rbpm)*                                                           |                                                                                                                                                                                                                                                                                    |
|             | -   *Effects of polystyrene microplastics on freshwater organisms - [Di Wu](presenters.qmd#sec-di-wu-rbpm)*                                                                                                                        | [Seminar Room 2](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NThmNGVkNTMtZGFjZC00Nzc1LWIwYWEtODU4ZTc1ZWE3ZDdk%40thread.v2/0?context=%7b%22Tid%22%3a%22bdeaeda8-c81d-45ce-863e-5232a535b7cb%22%2c%22Oid%22%3a%22e00978be-e503-49b1-931a-507f7901b187%22%7d)\             |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:45-11:05 | Coffee and Tea Break                                                                                                                                                                                                               | SoG Foyer                                                                                                                                                                                                                                                                          |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:05-12:05 | [Session 3: Geography Remix- Agent-based Models and Glaciology, Chair: Hannah Barnett]{.underline}                                                                                                                                 | [Seminar Room 2](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NThmNGVkNTMtZGFjZC00Nzc1LWIwYWEtODU4ZTc1ZWE3ZDdk%40thread.v2/0?context=%7b%22Tid%22%3a%22bdeaeda8-c81d-45ce-863e-5232a535b7cb%22%2c%22Oid%22%3a%22e00978be-e503-49b1-931a-507f7901b187%22%7d)              |
|             |                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                    |
|             | -   *Simulating Social Network Impacts on Meat-Eating Patterns: An Agent-Based Approach - [Xitong Dai](presenters.qmd#sec-xitong-dai-isds)*                                                                                        | <br>                                                                                                                                                                                                                                                                               |
|             | -   *Case Study on Calibration Methods for a High-Dimensional Global Trade Agent-Based Model - [Kejian Li](presenters.qmd#sec-kejian-li-isds)*                                                                                     |                                                                                                                                                                                                                                                                                    |
|             | -   *Ice Marginal Lakes Enhance Glacier Velocities across Greenland - [Connie Harpur](presenters.qmd#sec-connie-harpur-rbpm)*                                                                                                      | <br>                                                                                                                                                                                                                                                                               |
|             | -   *Using ICESat-2 to estimate the Depth of Supraglacial Ponds - [Jamie Izzard](presenters.qmd#sec-jamie-izzard-rbpm)*                                                                                                            |                                                                                                                                                                                                                                                                                    |
|             |                                                                                                                                                                                                                                    | <br>                                                                                                                                                                                                                                                                               |
|             | [Session 4: Geography Remix - Urbanisation and Remote Sensing , Chair: Rafa Mendes-Browne]{.underline}                                                                                                                             |                                                                                                                                                                                                                                                                                    |
|             |                                                                                                                                                                                                                                    | <br>                                                                                                                                                                                                                                                                               |
|             | -   *State-led mega urbanization project in inner Shanghai, China - [Youhua Chen](presenters.qmd#sec-youhua-chen-sjcc)*                                                                                                            |                                                                                                                                                                                                                                                                                    |
|             | -   *Uneven Entrepreneurial Governance: Imagining Urban Regeneration in State-Owned Industrial Communities of Chinese Small Industrial City* - [Yue Che](presenters.qmd#sec-yue-che-sjcc)                                          | <br>                                                                                                                                                                                                                                                                               |
|             | -   *Spatio-temporal trends and processes in desertification in Africa and Europe - [Jisung Kim](presenters.qmd#sec-jisung-kim-egc)*                                                                                               |                                                                                                                                                                                                                                                                                    |
|             | -   *The reflectance behaviour of European soils with increasing soil moisture content - [Denise Hick](presenters.qmd#sec-denise-hick-egc)*                                                                                        | [Seminar Room 1](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWE2YWQ0MjctM2UyMS00M2RlLTljZTktZjBhNjdhMDdiODQ1%40thread.v2/0?context=%7b%22Tid%22%3a%22bdeaeda8-c81d-45ce-863e-5232a535b7cb%22%2c%22Oid%22%3a%22e00978be-e503-49b1-931a-507f7901b187%22%7d)              |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:05-13:05 | Lunch                                                                                                                                                                                                                              | SoG Foyer                                                                                                                                                                                                                                                                          |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13:05-14:05 | [Session 5: Innovative Research Methods: Sanola Sandiford]{.underline}                                                                                                                                                             | [Seminar Room 1](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWE2YWQ0MjctM2UyMS00M2RlLTljZTktZjBhNjdhMDdiODQ1%40thread.v2/0?context=%7b%22Tid%22%3a%22bdeaeda8-c81d-45ce-863e-5232a535b7cb%22%2c%22Oid%22%3a%22e00978be-e503-49b1-931a-507f7901b187%22%7d) <br><br><br> |
|             |                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                    |
|             | -   *Embedding public art: a long term approach to serving post-industrial communities- [Katie Lee](presenters.qmd#sec-katie-lee-sjcc)*                                                                                            | <br>                                                                                                                                                                                                                                                                               |
|             | -   *The Production of Racially Mixed Identity in the British Music Industry - [Rafa Mendes-Browne](presenters.qmd#sec-rafa-mendes-browne-sjcc)*                                                                                   |                                                                                                                                                                                                                                                                                    |
|             | -   *Feminist Participatory (Creative) Action Research on Climate Change - [Andi Pratiwi](presenters.qmd#sec-andi-pratiwi-sjcc)*                                                                                                   | <br>                                                                                                                                                                                                                                                                               |
|             |                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                    |
|             | [Session 6: Geography Remix, Chair: (Hannah Barnett)]{.underline}                                                                                                                                                                  | <br>                                                                                                                                                                                                                                                                               |
|             |                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                    |
|             | -   *Pecking Away at Pollution: The Environmental Challenge of Veterinary Medicines in Poultry Litter! [- Beth Adams](presenters.qmd#sec-beth-adams-rbpm)*                                                                         | [Seminar Room 2](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NThmNGVkNTMtZGFjZC00Nzc1LWIwYWEtODU4ZTc1ZWE3ZDdk%40thread.v2/0?context=%7b%22Tid%22%3a%22bdeaeda8-c81d-45ce-863e-5232a535b7cb%22%2c%22Oid%22%3a%22e00978be-e503-49b1-931a-507f7901b187%22%7d)              |
|             | -   *Quantifying sediment loss from riverbanks attributable to the presence of invasive Impatiens glandulifera - [Beany Townsend](presenters.qmd#sec-beany-townsend-rbpm)*                                                         |                                                                                                                                                                                                                                                                                    |
|             | -   ***'**We only go as far as bikes go: researching scalar submissiveness with mobilities.' - [Tilen Kolar](presenters.qmd#sec-tilen-kolar-sjcc)*                                                                                 |                                                                                                                                                                                                                                                                                    |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:05-14:40 | Poster Session                                                                                                                                                                                                                     | SoG Foyer                                                                                                                                                                                                                                                                          |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:40-15:30 | Career's Talk - *Steve Carter, Careers Centre*                                                                                                                                                                                     | Seminar Room 1                                                                                                                                                                                                                                                                     |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15:30-16:00 | Academic Careers Panel - Dr Laura Loyola-Hernández, Dr Asa Roast, Keiran Suchak, Dr Liam Taylor                                                                                                                                    | Seminar Room 1                                                                                                                                                                                                                                                                     |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16:00-16:15 | Prizes and Closing Remarks                                                                                                                                                                                                         | Seminar Room 1                                                                                                                                                                                                                                                                     |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | Social!                                                                                                                                                                                                                            | Old Bar                                                                                                                                                                                                                                                                            |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
