---
title: "School of Geography PGR Conference 2025"
---

Welcome to the School of Geography PGR Conference at the University of Leeds. The conference will take place on the **3rd November 2025**, and is open to all **PGRs** and **academic staff** here at the School of Geography!

The PGR conference has been a longstanding event within the School of Geography to showcase the exiciting and important research from postgraduates. The conference provides an opportunity for postgraduates to present ongoing research, network with peers and develop new insights in a friendly and constructive setting. It is hoped that all postgraduates from across the School of Geography attend, whether presenting a talk, providing a poster, or coming along and engaging with your peers.

The School of Geography PGR conference will include:

-   **10-min** [presentations](Presentation.qmd) from postgraduates followed by **5-min** Q&A
-   First year PGR **lighting talk** [session](lightning.qmd)
-   [Poster](Poster.qmd) session & networking opportunity
-   Lunch & social

Lunch will be provided - however please **bring your own water bottle + mug** for refreshments!

### Key Dates

-   Deadline for registration: **13th October 2025** ([Register here](https://forms.office.com/e/b5dEUFB143))
-   Send powerpoint slides (if applicable) to gy17pls\@leeds.ac.uk: **31st October 2025**
-   SoG PGR Conference: **3rd November 2024.**

### Online Teams Links

TBC
